version: '3.8'

networks:
  elastic-stack:
    name: elastic-stack-network
    driver: bridge

services:
  nodejs-server:
    build: ./nodejs-server
    container_name: nodejs-server
    ports:
      - "3333:3333"
    networks:
      - elastic-stack
  
  golang-server:
    build: ./golang-server
    container_name: golang-server
    ports:
      - "3334:3334"
    networks:
      - elastic-stack
  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq/data/:/var/lib/rabbitmq
      - ./rabbitmq/log/:/var/log/rabbitmq
    networks:
      - elastic-stack