heartbeat.monitors:
- type: http
  schedule: '@every 5s'
  urls:
    - http://elasticsearch:9200
    - http://kibana:5601
    - http://rabbitmq:15672
    - http://nodejs-server:3333
    - http://golang-server:3335

- type: icmp
  schedule: '@every 5s'
  hosts:
    - elasticsearch
    - kibana
    - metricbeat
    - database
    - nodejs-server
    - golang-server
    - rabbitmq

processors:
- add_cloud_metadata: ~

output.elasticsearch:
  hosts: 'elasticsearch:9200'
  username: 'elastic'
  password: 'changeme'